In [66]:
import pandas as pd

In [67]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler ,LabelEncoder

In [68]:
df=pd.read_csv('Studen.csv')

In [69]:
print(df)

    Student_ID       Name   Age  Gender  Department  Attendance  Marks  \
0          101       Amit  20.0    Male         CSE        90.0   85.0
1          102      Priya  21.0  Female          IT        88.0   78.0
2          103      Rahul  22.0    Male         CSE         NaN   65.0
3          104      Sneha   NaN  Female        E&TC        95.0   92.0
4          105      Kiran  20.0    Male          IT        70.0    NaN
5          106      Pooja  23.0  Female         CSE        85.0   81.0
6          107        Raj  21.0    Male  Mechanical        60.0   55.0
7          108       Neha  22.0  Female       Civil        92.0   89.0
8          109      Arjun  20.0    Male         CSE        78.0   73.0
9          110      Kavya  24.0  Female          IT         NaN   68.0
10         111      Rohit  19.0    Male       Civil        82.0   75.0
11         112      Meena  21.0  Female        E&TC        96.0   94.0
12         113     Vishal  22.0    Male         CSE        75.0   71.0
13         114     Anjali  20.0  Female  Mechanical        80.0   76.0
14         115      Sagar  23.0    Male          IT        91.0   88.0
15         116       Riya  21.0  Female         CSE        89.0   84.0
16         117      Mohan  22.0    Male       Civil        55.0   49.0
17         118      Swati  20.0  Female          IT        97.0   95.0
18         119     Deepak  24.0    Male        E&TC        65.0   60.0
19         120       Asha  21.0  Female         CSE       100.0   98.0
20         121       Amit  20.0    Male         CSE        90.0   85.0
21         122      Priya  21.0  Female          IT        88.0   78.0
22         123      Rohan  19.0    Male         CSE        72.0   66.0
23         124     Shruti  22.0  Female       Civil        86.0   82.0
24         125     Nikhil  23.0    Male  Mechanical        79.0   74.0
25         126      Komal  20.0  Female        E&TC        93.0   91.0
26         127      Akash  21.0    Male         CSE        84.0   80.0
27         128    Pallavi  22.0  Female          IT        77.0   69.0
28         129      Sumit  24.0    Male       Civil        68.0   58.0
29         130  Vaishnavi  20.0  Female         CSE        98.0   97.0

          City    Income Placement
0         Pune   50000.0       Yes
1       Mumbai   45000.0       Yes
2       Nashik   38000.0        No
3         Pune   62000.0       Yes
4       Nagpur   35000.0        No
5       Mumbai       NaN       Yes
6         Pune   30000.0        No
7   Aurangabad   47000.0       Yes
8         Pune   51000.0       Yes
9       Mumbai   42000.0        No
10        Pune   39000.0       Yes
11      Nashik   68000.0       Yes
12        Pune   44000.0        No
13    Kolhapur   46000.0       Yes
14      Satara   53000.0       Yes
15        Pune   49000.0       Yes
16      Nagpur   25000.0        No
17      Mumbai   70000.0       Yes
18        Pune   36000.0        No
19        Pune  800000.0       Yes
20        Pune   50000.0       Yes
21      Mumbai   45000.0       Yes
22      Nashik   41000.0        No
23        Pune   48000.0       Yes
24  Aurangabad   52000.0        No
25      Mumbai   61000.0       Yes
26      Nagpur   43000.0       Yes
27    Kolhapur   39000.0        No
28      Satara   34000.0        No
29        Pune   72000.0       Yes

In [70]:
# Step 2: Check missing values
print('\nMissing Values:')
print(df.isnull().sum())

Missing Values:
Student_ID    0
Name          0
Age           1
Gender        0
Department    0
Attendance    2
Marks         1
City          0
Income        1
Placement     0
dtype: int64

In [71]:
# Step 3: Fill missing values
df[['Age','Attendance','Marks','Income']]=df[['Age','Attendance','Marks','Income']].fillna(df[['Age','Attendance','Marks','Income']].mean())

In [72]:
df

,Student_ID,Name,Age,Gender,Department,Attendance,Marks,City,Income,Placement
0,101,Amit,20.000000,Male,CSE,90.000000,85.000000,Pune,50000.000000,Yes
1,102,Priya,21.000000,Female,IT,88.000000,78.000000,Mumbai,45000.000000,Yes
2,103,Rahul,22.000000,Male,CSE,82.964286,65.000000,Nashik,38000.000000,No
3,104,Sneha,21.310345,Female,E&TC,95.000000,92.000000,Pune,62000.000000,Yes
4,105,Kiran,20.000000,Male,IT,70.000000,77.793103,Nagpur,35000.000000,No
5,106,Pooja,23.000000,Female,CSE,85.000000,81.000000,Mumbai,72931.034483,Yes
6,107,Raj,21.000000,Male,Mechanical,60.000000,55.000000,Pune,30000.000000,No
7,108,Neha,22.000000,Female,Civil,92.000000,89.000000,Aurangabad,47000.000000,Yes
8,109,Arjun,20.000000,Male,CSE,78.000000,73.000000,Pune,51000.000000,Yes
9,110,Kavya,24.000000,Female,IT,82.964286,68.000000,Mumbai,42000.000000,No
10,111,Rohit,19.000000,Male,Civil,82.000000,75.000000,Pune,39000.000000,Yes
11,112,Meena,21.000000,Female,E&TC,96.000000,94.000000,Nashik,68000.000000,Yes
12,113,Vishal,22.000000,Male,CSE,75.000000,71.000000,Pune,44000.000000,No
13,114,Anjali,20.000000,Female,Mechanical,80.000000,76.000000,Kolhapur,46000.000000,Yes
14,115,Sagar,23.000000,Male,IT,91.000000,88.000000,Satara,53000.000000,Yes
15,116,Riya,21.000000,Female,CSE,89.000000,84.000000,Pune,49000.000000,Yes
16,117,Mohan,22.000000,Male,Civil,55.000000,49.000000,Nagpur,25000.000000,No
17,118,Swati,20.000000,Female,IT,97.000000,95.000000,Mumbai,70000.000000,Yes
18,119,Deepak,24.000000,Male,E&TC,65.000000,60.000000,Pune,36000.000000,No
19,120,Asha,21.000000,Female,CSE,100.000000,98.000000,Pune,800000.000000,Yes
20,121,Amit,20.000000,Male,CSE,90.000000,85.000000,Pune,50000.000000,Yes
21,122,Priya,21.000000,Female,IT,88.000000,78.000000,Mumbai,45000.000000,Yes
22,123,Rohan,19.000000,Male,CSE,72.000000,66.000000,Nashik,41000.000000,No
23,124,Shruti,22.000000,Female,Civil,86.000000,82.000000,Pune,48000.000000,Yes
24,125,Nikhil,23.000000,Male,Mechanical,79.000000,74.000000,Aurangabad,52000.000000,No
25,126,Komal,20.000000,Female,E&TC,93.000000,91.000000,Mumbai,61000.000000,Yes
26,127,Akash,21.000000,Male,CSE,84.000000,80.000000,Nagpur,43000.000000,Yes
27,128,Pallavi,22.000000,Female,IT,77.000000,69.000000,Kolhapur,39000.000000,No
28,129,Sumit,24.000000,Male,Civil,68.000000,58.000000,Satara,34000.000000,No
29,130,Vaishnavi,20.000000,Female,CSE,98.000000,97.000000,Pune,72000.000000,Yes

In [73]:
df.isnull().sum()

Student_ID    0
Name          0
Age           0
Gender        0
Department    0
Attendance    0
Marks         0
City          0
Income        0
Placement     0
dtype: int64

In [74]:
# Step 4: Remove duplicate records
print(df.duplicated())

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
dtype: bool

In [75]:
df = df.drop_duplicates()

In [76]:
# Step 5: Handle outliers using IQR

In [77]:
Q1=df['Income'].quantile(0.25)
Q3=df['Income'].quantile(0.75)

In [78]:
IQR =Q3-Q1

In [79]:
lower= Q1-1.5 * IQR
upper= Q3+1.5 * IQR

In [80]:
quantiles=df[(df['Income']> lower) |
             (df['Income']<upper)
            ]

In [81]:
print("Q1:", Q1)
print("Q2:", Q3)
print("IQR:", IQR)
print("Lower Bound:", lower)
print("Upper Bound:", upper)

Q1: 39500.0
Q2: 52750.0
IQR: 13250.0
Lower Bound: 19625.0
Upper Bound: 72625.0

In [82]:
# Handle outliers
df['Income'] = df['Income'].clip(lower, upper)

In [83]:
print(df['Income'])

0     50000.0
1     45000.0
2     38000.0
3     62000.0
4     35000.0
5     72625.0
6     30000.0
7     47000.0
8     51000.0
9     42000.0
10    39000.0
11    68000.0
12    44000.0
13    46000.0
14    53000.0
15    49000.0
16    25000.0
17    70000.0
18    36000.0
19    72625.0
20    50000.0
21    45000.0
22    41000.0
23    48000.0
24    52000.0
25    61000.0
26    43000.0
27    39000.0
28    34000.0
29    72000.0
Name: Income, dtype: float64

In [84]:
# Step 6: Label Encoding
df['Gender']=df['Gender'].map({'Female':0,'Male':1})

In [85]:
df

,Student_ID,Name,Age,Gender,Department,Attendance,Marks,City,Income,Placement
0,101,Amit,20.000000,1,CSE,90.000000,85.000000,Pune,50000.0,Yes
1,102,Priya,21.000000,0,IT,88.000000,78.000000,Mumbai,45000.0,Yes
2,103,Rahul,22.000000,1,CSE,82.964286,65.000000,Nashik,38000.0,No
3,104,Sneha,21.310345,0,E&TC,95.000000,92.000000,Pune,62000.0,Yes
4,105,Kiran,20.000000,1,IT,70.000000,77.793103,Nagpur,35000.0,No
5,106,Pooja,23.000000,0,CSE,85.000000,81.000000,Mumbai,72625.0,Yes
6,107,Raj,21.000000,1,Mechanical,60.000000,55.000000,Pune,30000.0,No
7,108,Neha,22.000000,0,Civil,92.000000,89.000000,Aurangabad,47000.0,Yes
8,109,Arjun,20.000000,1,CSE,78.000000,73.000000,Pune,51000.0,Yes
9,110,Kavya,24.000000,0,IT,82.964286,68.000000,Mumbai,42000.0,No
10,111,Rohit,19.000000,1,Civil,82.000000,75.000000,Pune,39000.0,Yes
11,112,Meena,21.000000,0,E&TC,96.000000,94.000000,Nashik,68000.0,Yes
12,113,Vishal,22.000000,1,CSE,75.000000,71.000000,Pune,44000.0,No
13,114,Anjali,20.000000,0,Mechanical,80.000000,76.000000,Kolhapur,46000.0,Yes
14,115,Sagar,23.000000,1,IT,91.000000,88.000000,Satara,53000.0,Yes
15,116,Riya,21.000000,0,CSE,89.000000,84.000000,Pune,49000.0,Yes
16,117,Mohan,22.000000,1,Civil,55.000000,49.000000,Nagpur,25000.0,No
17,118,Swati,20.000000,0,IT,97.000000,95.000000,Mumbai,70000.0,Yes
18,119,Deepak,24.000000,1,E&TC,65.000000,60.000000,Pune,36000.0,No
19,120,Asha,21.000000,0,CSE,100.000000,98.000000,Pune,72625.0,Yes
20,121,Amit,20.000000,1,CSE,90.000000,85.000000,Pune,50000.0,Yes
21,122,Priya,21.000000,0,IT,88.000000,78.000000,Mumbai,45000.0,Yes
22,123,Rohan,19.000000,1,CSE,72.000000,66.000000,Nashik,41000.0,No
23,124,Shruti,22.000000,0,Civil,86.000000,82.000000,Pune,48000.0,Yes
24,125,Nikhil,23.000000,1,Mechanical,79.000000,74.000000,Aurangabad,52000.0,No
25,126,Komal,20.000000,0,E&TC,93.000000,91.000000,Mumbai,61000.0,Yes
26,127,Akash,21.000000,1,CSE,84.000000,80.000000,Nagpur,43000.0,Yes
27,128,Pallavi,22.000000,0,IT,77.000000,69.000000,Kolhapur,39000.0,No
28,129,Sumit,24.000000,1,Civil,68.000000,58.000000,Satara,34000.0,No
29,130,Vaishnavi,20.000000,0,CSE,98.000000,97.000000,Pune,72000.0,Yes

In [98]:
# Step 7: Normalization
features = ['Attendance']

In [99]:
scaler = MinMaxScaler()

In [100]:
df[features] = scaler.fit_transform(df[features])

In [101]:
df

,Student_ID,Name,Age,Gender,Department,Attendance,Marks,City,Income,Placement
0,101,Amit,20.000000,1,CSE,0.777778,0.573062,Pune,50000.0,Yes
1,102,Priya,21.000000,0,IT,0.733333,0.016452,Mumbai,45000.0,Yes
2,103,Rahul,22.000000,1,CSE,0.621429,-1.017254,Nashik,38000.0,No
3,104,Sneha,21.310345,0,E&TC,0.888889,1.129673,Pune,62000.0,Yes
4,105,Kiran,20.000000,1,IT,0.333333,0.000000,Nagpur,35000.0,No
5,106,Pooja,23.000000,0,CSE,0.666667,0.254999,Mumbai,72625.0,Yes
6,107,Raj,21.000000,1,Mechanical,0.111111,-1.812412,Pune,30000.0,No
7,108,Neha,22.000000,0,Civil,0.822222,0.891126,Aurangabad,47000.0,Yes
8,109,Arjun,20.000000,1,CSE,0.511111,-0.381128,Pune,51000.0,Yes
9,110,Kavya,24.000000,0,IT,0.621429,-0.778707,Mumbai,42000.0,No
10,111,Rohit,19.000000,1,Civil,0.600000,-0.222096,Pune,39000.0,Yes
11,112,Meena,21.000000,0,E&TC,0.911111,1.288705,Nashik,68000.0,Yes
12,113,Vishal,22.000000,1,CSE,0.444444,-0.540159,Pune,44000.0,No
13,114,Anjali,20.000000,0,Mechanical,0.555556,-0.142580,Kolhapur,46000.0,Yes
14,115,Sagar,23.000000,1,IT,0.800000,0.811610,Satara,53000.0,Yes
15,116,Riya,21.000000,0,CSE,0.755556,0.493546,Pune,49000.0,Yes
16,117,Mohan,22.000000,1,Civil,0.000000,-2.289507,Nagpur,25000.0,No
17,118,Swati,20.000000,0,IT,0.933333,1.368221,Mumbai,70000.0,Yes
18,119,Deepak,24.000000,1,E&TC,0.222222,-1.414833,Pune,36000.0,No
19,120,Asha,21.000000,0,CSE,1.000000,1.606768,Pune,72625.0,Yes
20,121,Amit,20.000000,1,CSE,0.777778,0.573062,Pune,50000.0,Yes
21,122,Priya,21.000000,0,IT,0.733333,0.016452,Mumbai,45000.0,Yes
22,123,Rohan,19.000000,1,CSE,0.377778,-0.937738,Nashik,41000.0,No
23,124,Shruti,22.000000,0,Civil,0.688889,0.334515,Pune,48000.0,Yes
24,125,Nikhil,23.000000,1,Mechanical,0.533333,-0.301612,Aurangabad,52000.0,No
25,126,Komal,20.000000,0,E&TC,0.844444,1.050157,Mumbai,61000.0,Yes
26,127,Akash,21.000000,1,CSE,0.644444,0.175483,Nagpur,43000.0,Yes
27,128,Pallavi,22.000000,0,IT,0.488889,-0.699191,Kolhapur,39000.0,No
28,129,Sumit,24.000000,1,Civil,0.288889,-1.573865,Satara,34000.0,No
29,130,Vaishnavi,20.000000,0,CSE,0.955556,1.527252,Pune,72000.0,Yes

In [102]:
# Step 8: Standardization
features = ['Marks']

In [103]:
scaler = StandardScaler()

In [104]:
df[features] = scaler.fit_transform(df[features])

In [105]:
df

,Student_ID,Name,Age,Gender,Department,Attendance,Marks,City,Income,Placement
0,101,Amit,20.000000,1,CSE,0.777778,5.730623e-01,Pune,50000.0,Yes
1,102,Priya,21.000000,0,IT,0.733333,1.645155e-02,Mumbai,45000.0,Yes
2,103,Rahul,22.000000,1,CSE,0.621429,-1.017254e+00,Nashik,38000.0,No
3,104,Sneha,21.310345,0,E&TC,0.888889,1.129673e+00,Pune,62000.0,Yes
4,105,Kiran,20.000000,1,IT,0.333333,-3.330669e-16,Nagpur,35000.0,No
5,106,Pooja,23.000000,0,CSE,0.666667,2.549990e-01,Mumbai,72625.0,Yes
6,107,Raj,21.000000,1,Mechanical,0.111111,-1.812412e+00,Pune,30000.0,No
7,108,Neha,22.000000,0,Civil,0.822222,8.911256e-01,Aurangabad,47000.0,Yes
8,109,Arjun,20.000000,1,CSE,0.511111,-3.811276e-01,Pune,51000.0,Yes
9,110,Kavya,24.000000,0,IT,0.621429,-7.787067e-01,Mumbai,42000.0,No
10,111,Rohit,19.000000,1,Civil,0.600000,-2.220959e-01,Pune,39000.0,Yes
11,112,Meena,21.000000,0,E&TC,0.911111,1.288705e+00,Nashik,68000.0,Yes
12,113,Vishal,22.000000,1,CSE,0.444444,-5.401592e-01,Pune,44000.0,No
13,114,Anjali,20.000000,0,Mechanical,0.555556,-1.425801e-01,Kolhapur,46000.0,Yes
14,115,Sagar,23.000000,1,IT,0.800000,8.116098e-01,Satara,53000.0,Yes
15,116,Riya,21.000000,0,CSE,0.755556,4.935465e-01,Pune,49000.0,Yes
16,117,Mohan,22.000000,1,Civil,0.000000,-2.289507e+00,Nagpur,25000.0,No
17,118,Swati,20.000000,0,IT,0.933333,1.368221e+00,Mumbai,70000.0,Yes
18,119,Deepak,24.000000,1,E&TC,0.222222,-1.414833e+00,Pune,36000.0,No
19,120,Asha,21.000000,0,CSE,1.000000,1.606768e+00,Pune,72625.0,Yes
20,121,Amit,20.000000,1,CSE,0.777778,5.730623e-01,Pune,50000.0,Yes
21,122,Priya,21.000000,0,IT,0.733333,1.645155e-02,Mumbai,45000.0,Yes
22,123,Rohan,19.000000,1,CSE,0.377778,-9.377383e-01,Nashik,41000.0,No
23,124,Shruti,22.000000,0,Civil,0.688889,3.345148e-01,Pune,48000.0,Yes
24,125,Nikhil,23.000000,1,Mechanical,0.533333,-3.016117e-01,Aurangabad,52000.0,No
25,126,Komal,20.000000,0,E&TC,0.844444,1.050157e+00,Mumbai,61000.0,Yes
26,127,Akash,21.000000,1,CSE,0.644444,1.754832e-01,Nagpur,43000.0,Yes
27,128,Pallavi,22.000000,0,IT,0.488889,-6.991909e-01,Kolhapur,39000.0,No
28,129,Sumit,24.000000,1,Civil,0.288889,-1.573865e+00,Satara,34000.0,No
29,130,Vaishnavi,20.000000,0,CSE,0.955556,1.527252e+00,Pune,72000.0,Yes

In [106]:
print("COMPLITE DATASET:")
print(df)

COMPLITE DATASET:
    Student_ID       Name        Age  Gender  Department  Attendance  \
0          101       Amit  20.000000       1         CSE    0.777778
1          102      Priya  21.000000       0          IT    0.733333
2          103      Rahul  22.000000       1         CSE    0.621429
3          104      Sneha  21.310345       0        E&TC    0.888889
4          105      Kiran  20.000000       1          IT    0.333333
5          106      Pooja  23.000000       0         CSE    0.666667
6          107        Raj  21.000000       1  Mechanical    0.111111
7          108       Neha  22.000000       0       Civil    0.822222
8          109      Arjun  20.000000       1         CSE    0.511111
9          110      Kavya  24.000000       0          IT    0.621429
10         111      Rohit  19.000000       1       Civil    0.600000
11         112      Meena  21.000000       0        E&TC    0.911111
12         113     Vishal  22.000000       1         CSE    0.444444
13         114     Anjali  20.000000       0  Mechanical    0.555556
14         115      Sagar  23.000000       1          IT    0.800000
15         116       Riya  21.000000       0         CSE    0.755556
16         117      Mohan  22.000000       1       Civil    0.000000
17         118      Swati  20.000000       0          IT    0.933333
18         119     Deepak  24.000000       1        E&TC    0.222222
19         120       Asha  21.000000       0         CSE    1.000000
20         121       Amit  20.000000       1         CSE    0.777778
21         122      Priya  21.000000       0          IT    0.733333
22         123      Rohan  19.000000       1         CSE    0.377778
23         124     Shruti  22.000000       0       Civil    0.688889
24         125     Nikhil  23.000000       1  Mechanical    0.533333
25         126      Komal  20.000000       0        E&TC    0.844444
26         127      Akash  21.000000       1         CSE    0.644444
27         128    Pallavi  22.000000       0          IT    0.488889
28         129      Sumit  24.000000       1       Civil    0.288889
29         130  Vaishnavi  20.000000       0         CSE    0.955556

           Marks        City   Income Placement
0   5.730623e-01        Pune  50000.0       Yes
1   1.645155e-02      Mumbai  45000.0       Yes
2  -1.017254e+00      Nashik  38000.0        No
3   1.129673e+00        Pune  62000.0       Yes
4  -3.330669e-16      Nagpur  35000.0        No
5   2.549990e-01      Mumbai  72625.0       Yes
6  -1.812412e+00        Pune  30000.0        No
7   8.911256e-01  Aurangabad  47000.0       Yes
8  -3.811276e-01        Pune  51000.0       Yes
9  -7.787067e-01      Mumbai  42000.0        No
10 -2.220959e-01        Pune  39000.0       Yes
11  1.288705e+00      Nashik  68000.0       Yes
12 -5.401592e-01        Pune  44000.0        No
13 -1.425801e-01    Kolhapur  46000.0       Yes
14  8.116098e-01      Satara  53000.0       Yes
15  4.935465e-01        Pune  49000.0       Yes
16 -2.289507e+00      Nagpur  25000.0        No
17  1.368221e+00      Mumbai  70000.0       Yes
18 -1.414833e+00        Pune  36000.0        No
19  1.606768e+00        Pune  72625.0       Yes
20  5.730623e-01        Pune  50000.0       Yes
21  1.645155e-02      Mumbai  45000.0       Yes
22 -9.377383e-01      Nashik  41000.0        No
23  3.345148e-01        Pune  48000.0       Yes
24 -3.016117e-01  Aurangabad  52000.0        No
25  1.050157e+00      Mumbai  61000.0       Yes
26  1.754832e-01      Nagpur  43000.0       Yes
27 -6.991909e-01    Kolhapur  39000.0        No
28 -1.573865e+00      Satara  34000.0        No
29  1.527252e+00        Pune  72000.0       Yes